### ISSUE TITLE
Show signing key on Sign Message request window

### ISSUE THREAD

**Issue by davidatwhiletrue** [casper-ecosystem/casper-manager#4]
I think it would be good to show the signing key when the user is requested to sign a message:

![image](https://github.com/casper-ecosystem/casper-manager/assets/2131247/37f97e59-d84d-46ee-a8bb-685d17f39691)

**Comment by KillianH** [comment]
Agree. We can improve this screen. Let me know if you want to do the PR. Otherwise I'll try to do it asap.

**Comment by davidatwhiletrue** [comment]
Thanks @KillianH. I'm not familiar with the code. I'd ask you to do it ;)

**Comment by KillianH** [comment]
> Thanks @KillianH. I'm not familiar with the code. I'd ask you to do it ;)

@davidatwhiletrue Like this ? Any comment or other improvement to do overall ?

![image](https://github.com/casper-ecosystem/casper-manager/assets/8064210/ba7d879a-0b4e-4b70-ad84-cfe9065c47f0)

**Comment by davidatwhiletrue** [comment]
Hey @KillianH , this looks good. Just one question, why there're two different origins in the screenshot? `localhost:9000` and `localhost:8080`

**Comment by KillianH** [comment]
The 9000 is the local dev server of the snap instead of pointing to a specific npm package

**Comment by KillianH** [comment]
https://www.npmjs.com/package/casper-manager @davidatwhiletrue You can use the 1.0.4 version with Metamask Flask for your local / live test envs. I'll send a request to Metamask to update the snap to 1.0.4 in the live version of Metamask asap.

**Comment by KillianH** [comment]
https://github.com/MetaMask/snaps-registry/pull/253
